spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/battle_ships_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    password: Albert.nustiu.2002
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update