spring:
  datasource:
    password: Albert.nustiu.2002
    username: root
    url: "jdbc:mysql://localhost:3306/employees_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect



  mvc:
    hiddenmethod:
      filter:
        enabled: true