spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/super_market_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    username: root
    password: Albert.nustiu.2002
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

    show-sql: true
