spring:
  datasource:
    username: root
    password: Albert.nustiu.2002
    url: jdbc:mysql://localhost:3306/zoo_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

    properties:
      hibernate:
        format_sql: true