spring:
  datasource:
    password: Albert.nustiu.2002
    username: root
    driver-class-name: com.mysql.jdbc.Driver

 jpa:
   show-sql: true
   properties:
     hibernate:
       format_sql: true
   database-platform: org.hibernate.MySQL8Dialect
  hibernate:
    ddl-auto: update