spring:
  datasource:
    username: root
    password: Albert.nustiu.2002
    url: "jdbc:mysql://localhost:3306/app_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
